### ISSUE TITLE
port index out of range

### ISSUE THREAD

**Issue by hunter-goller** [kfreitag1/LaptopAmbilight#1]
['COM7']
Which port? (0-?)7
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    main()
  File "main.py", line 25, in main
    port = ports[int(input("Which port? (0-?)"))]
IndexError: list index out of range

How would I fix this? I am using Python 3.8.0

**Comment by hunter-goller** [comment]
okay so it must have been port 0, because that worked but my LEDs do not light up,

**Comment by MSAR8** [comment]
code is running fine but LED's only light up as white, they don't change color. Did you find the fix for your problem? @HunterG6700

**Comment by hunter-goller** [comment]
> code is running fine but LED's only light up as white, they don't change color. Did you find the fix for your problem? @HunterG6700

I run the pyghon script and nothing happens for me. It just prints sending init data and bkthing happens after that.

**Comment by MSAR8** [comment]
> > code is running fine but LED's only light up as white, they don't change color. Did you find the fix for your problem? @HunterG6700
> 
> I run the pyghon script and nothing happens for me. It just prints sending init data and bkthing happens after that.

yeah same thing man.... i think there is some problem with arduino script. The script is not reading data from the serial communication port and as you cannot open the serial monitor because it says port is busy when python script is running cant figure out the error.
Let me know if you find some solution or some different script that works similarly.

**Comment by hunter-goller** [comment]
> > > code is running fine but LED's only light up as white, they don't change color. Did you find the fix for your problem? @HunterG6700
> > 
> > 
> > I run the pyghon script and nothing happens for me. It just prints sending init data and bkthing happens after that.
> 
> yeah same thing man.... i think there is some problem with arduino script. The script is not reading data from the serial communication port and as you cannot open the serial monitor because it says port is busy when python script is running cant figure out the error.
> Let me know if you find some solution or some different script that works similarly.

Maybe try it with a ESP8266 , but it should have worked with an ardruin0
