### ISSUE TITLE
    img = img.reduce(REDUCTION_FACTOR) AttributeError: 'Image' object has no attribute 'reduce'

### ISSUE THREAD

**Issue by MSAR8** [kfreitag1/LaptopAmbilight#2]
['COM3', 'COM15', 'COM11', 'COM6', 'COM8', 'COM4', 'COM12', 'COM10', 'COM7', 'COM5', 'COM9']
Which port? (0-?)1
How many LEDS on the sides?21
How many LEDS on the top?32
How fast to fade? (5-60)20
bytearray(b'J\x14')
Sending init data...
b'6'
b'7'
Traceback (most recent call last):
  File "D:\softwares\Laptop Ambilight\LaptopAmbilight-master\LaptopAmbilight-master\main.py", line 130, in <module>
    main()
  File "D:\softwares\Laptop Ambilight\LaptopAmbilight-master\LaptopAmbilight-master\main.py", line 60, in main
    pixel_bytes = getByteArrayForScreen(sct)
  File "D:\softwares\Laptop Ambilight\LaptopAmbilight-master\LaptopAmbilight-master\main.py", line 91, in getByteArrayForScreen
    img = img.reduce(REDUCTION_FACTOR)
AttributeError: 'Image' object has no attribute 'reduce'

**Comment by MSAR8** [comment]
upgrading pillow library fixed the issue
